name: CI + CD

on:
  push:
    branches: [ manual ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
#      - name: Compile
#        run: echo Hello, world!
      - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
